-- Schema version: v1.0.0

-- Creating initial tables

CREATE DATABASE task_management;
USE task_management;

CREATE TABLE TASK_USER (
    ID BIGINT PRIMARY KEY  AUTO_INCREMENT,
    TASK_USER_ID VARCHAR(50) UNIQUE NOT NULL ,
    NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(256) UNIQUE NOT NULL,
    DOB DATE NOT NULL,
    GENDER ENUM('MALE', 'FEMALE', 'OTHER') NOT NULL,
    STATUS VARCHAR(15) NOT NULL CHECK(STATUS IN ('ACTIVE','INACTIVE')),
    USER_ROLE VARCHAR(50) CHECK (USER_ROLE IN ('USER', 'ADMIN')) NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP DEFAULT NULL
);

CREATE TABLE USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL UNIQUE,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    STATUS VARCHAR(255) CHECK (STATUS IN ('ACTIVE', 'INACTIVE','BLOCKED','DELETED')) NOT NULL,
    USER_ROLE VARCHAR(50) CHECK (USER_ROLE IN ('USER', 'ADMIN')) NOT NULL,
    CREATED_ON TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE SESSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    USER_ROLE VARCHAR(50) CHECK (USER_ROLE IN ('USER', 'ADMIN')) NOT NULL,
    TOKEN TEXT NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRY_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_SESSION_USER_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE RESTRICT,
    CONSTRAINT FK_SESSION_USER_USERNAME FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME) ON DELETE RESTRICT
);


CREATE TABLE TASK (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TASK_ID VARCHAR(50) NOT NULL UNIQUE,
    TITLE VARCHAR(250) NOT NULL,
    DESCRIPTION VARCHAR(500) NOT NULL,
    STATUS VARCHAR(15) NOT NULL CHECK(STATUS IN ('PENDING','IN_PROGRESS','COMPLETED','DELETED')),
    DUE_DATE DATE DEFAULT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP DEFAULT NULL,
    DELETED_ON TIMESTAMP DEFAULT NULL,
    CREATED_BY VARCHAR(50) NOT NULL,
    UPDATED_BY VARCHAR(50) DEFAULT NULL,
    DELETED_BY VARCHAR(50) DEFAULT NULL,
    PRIMARY KEY (ID)
);


