-- Schema version: v1.0.0

-- Creating initial tables

CREATE DATABASE taskmanagement;
USE taskmanagement;



CREATE TABLE USER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL UNIQUE,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    OTP VARCHAR(10) NOT NULL,
    STATUS VARCHAR(255) CHECK (STATUS IN ('ACTIVE', 'INACTIVE','BLOCKED','DELETED')) NOT NULL,
    USER_ROLE VARCHAR(50) CHECK (USER_ROLE IN ('USER')) NOT NULL,
    CREATED_ON TIMESTAMP  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE SESSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(30) NOT NULL,
    USER_ROLE VARCHAR(15) NOT NULL,
    TOKEN TEXT NOT NULL,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRY_AT TIMESTAMP NOT NULL,
    CONSTRAINT FK_SESSION_LOAN_USER_USER_ID FOREIGN KEY (USER_ID) REFERENCES LOAN_USER(USER_ID) ON DELETE RESTRICT,
    CONSTRAINT FK_SESSION_LOAN_USER_USERNAME FOREIGN KEY (USERNAME) REFERENCES LOAN_USER(USERNAME) ON DELETE RESTRICT
);





CREATE TABLE TASK_USER (
    ID BIGINT PRIMARY KEY  AUTO_INCREMENT,
    TASK_USER_ID VARCHAR(50) UNIQUE NOT NULL ,
    NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(256) UNIQUE NOT NULL,
    PHONE VARCHAR(256) UNIQUE NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PINCODE VARCHAR(10) NOT NULL,
    STATUS VARCHAR(15) NOT NULL CHECK(STATUS IN ('ACTIVE','INACTIVE')),
    DOB DATE NOT NULL,
    PROFILE_PIC MEDIUMBLOB,
    EMAIL_VERIFIED BOOLEAN,
    PHONE_VERIFIED BOOLEAN,
    CREATED_ON TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_ON TIMESTAMP DEFAULT NULL
);
